/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f8fafb",
        "surface-dim": "#d8dadb",
        "surface-bright": "#f8fafb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f5",
        "surface-container": "#eceeef",
        "surface-container-high": "#e6e8e9",
        "surface-container-highest": "#e1e3e4",
        "on-surface": "#191c1d",
        "on-surface-variant": "#3e484c",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#eff1f2",
        "outline": "#6e797d",
        "outline-variant": "#bdc8cc",
        "surface-tint": "#00687b",
        "primary": "#006578",
        "on-primary": "#ffffff",
        "primary-container": "#008097",
        "on-primary-container": "#f9fdff",
        "inverse-primary": "#71d4ef",
        "secondary": "#565e74",
        "on-secondary": "#ffffff",
        "secondary-container": "#dae2fd",
        "on-secondary-container": "#5c647a",
        "tertiary": "#006672",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#008190",
        "on-tertiary-container": "#f7feff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#afecff",
        "primary-fixed-dim": "#71d4ef",
        "on-primary-fixed": "#001f26",
        "on-primary-fixed-variant": "#004e5d",
        "secondary-fixed": "#dae2fd",
        "secondary-fixed-dim": "#bec6e0",
        "on-secondary-fixed": "#131b2e",
        "on-secondary-fixed-variant": "#3f465c",
        "tertiary-fixed": "#9bf0ff",
        "tertiary-fixed-dim": "#49d8ed",
        "on-tertiary-fixed": "#001f24",
        "on-tertiary-fixed-variant": "#004f58",
        "background": "#f8fafb",
        "on-background": "#191c1d",
        "surface-variant": "#e1e3e4"
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "container-max": "1280px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "sidebar-width": "280px",
        "toolbar-height": "4rem",
        "margin-page": "2rem",
        "stack-gap": "1rem"
      },
      fontFamily: {
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}